version: "3"
containers:
  - name: cli
    image: ubuntu
    shell: /bin/bash
    memory: 256
virtualmachines:
  - name: jumpstation
    image: ubuntu-os-cloud/ubuntu-2004-lts
    shell: /bin/bash
    machine_type: n1-standard-4
    allow_external_ingress:
    - http
    - https
    - high-ports
  - name: airgap
    image: kots-field-labs/instruqt-airgap
    shell: /bin/bash
    machine_type: n1-standard-8