apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-check-pod
  labels:
    app: file-check-pod
spec:
  selector:
    matchLabels:
      app: file-check-pod
  template:
    metadata:
      labels:
        app: file-check-pod
    spec:
      volumes:
        - name: lab1-config
          hostPath:
            path: /etc/lab2/
      containers:
        - name: busybox
          image: busybox
          args:
            - sleep
            - infinity
          volumeMounts:
            - mountPath: /etc/lab2
              name: lab1-config
          resources:
            limits:
              memory: '256Mi'
              cpu: '500m'
            requests:
              memory: '32Mi'
              cpu: '100m'
